### ISSUE TITLE
ImportError: cannot import name 'datasets' from partially initialized module 'detectron2.data'

### ISSUE THREAD

**Issue by junghyeon0427** [Therock90421/DA-Pro#4]
Hello, there is no datasets folder under the detectron2/data folder, so I think I'm getting the following error. How do I fix it?

<img width="1112" alt="Screenshot 2024-03-05 at 12 24 12" src="https://github.com/Therock90421/DA-Pro/assets/77001598/62de7a4a-6f2b-4cdf-b88b-322ecd04aa78">

**Comment by Therock90421** [comment]
Thanks for pointing that out :)
I have just updated the dataset folder under detectron2/data.
